### PR TITLE
Stage 1 1 markup

### PR DESCRIPTION
**Pull request by adervishaj-afk**

### CODE REVIEW

**Comment by n817** [comment]
Hello! Great job with your first diploma stage! The project looks very good in general, but will require some refactoring. Please find comments below and make necessary corrections.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* It's necessary to download and connect file `normalize.css`.
You can download `normalize.css` here: https://necolas.github.io/normalize.css/
* It's necessary to download and connect fonts according to the design.
* On desktop 1440px:
    - `about` section doesn't match the design, it's necessary to fix it: https://drive.proton.me/urls/1WAVD62T40#5in3S2VdTVKL The project should match the design in the Figma.
    - `cards` section doesn't match the design, it's necessary to fix it. The project should match the design in the Figma.

* On tablet 768px:
    - The project doesn't match the design, it's necessary to fix it. The project should match the design in the Figma.

* On mobile 320px:
    - The project doesn't match the design, it's necessary to fix it. The project should match the design in the Figma.

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Displays with a width of 320px+ have horizontal scrolling.

To find the elements that cause horizontal scrolling, you can use the `outline` CSS property and implement it globally:

`* {
  outline: 1px solid red;
}`

All the elements on the page will be outlined with a red line, and you'll be able to quickly find which of them is the cause of scrolling. Don't forget to delete this code before submitting it for review.

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* GitHub and Facebook links don't work, it's necessary to fix it.

- [ ]  Classes are named according to BEM specifications.

* `results__page-title` element can't be used without the `results` block as the parent (according to the BEM rules).

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 46

**Comment by adervishaj-afk** [comment]
Hey n817,

I just wanted to confirm. The changes that are needed are everything that's not currently checked off, correct?

**Comment by n817** [comment]
> Hey n817,
> 
> I just wanted to confirm. The changes that are needed are everything that's not currently checked off, correct?

Yes, that's correct.

**Comment by n817** [comment]
Hello! Thanks for the corrections, your project looks better! Several small issues in the code are left. Please find comments below and make necessary corrections.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* It's necessary to connect `normalize.css`. You can import this file into `index.css`.
* It's necessary to specify font-family for the `footer__link`, `search-button` and `search-input` elements.
* On tablet 768px:
    - The project doesn't match the design, it's necessary to fix it. The project should match the design in the Figma.

* On mobile 320px:
    - The project doesn't match the design, it's necessary to fix it. The project should match the design in the Figma.

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Displays with a width of 321px+ have horizontal scrolling.

To find the elements that cause horizontal scrolling, you can use the `outline` CSS property and implement it globally:

`* {
  outline: 1px solid red;
}`

All the elements on the page will be outlined with a red line, and you'll be able to quickly find which of them is the cause of scrolling. Don't forget to delete this code before submitting it for review.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

- [x]  Classes are named according to BEM specifications.

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.

* It's necessary to connect `fonts.css`. You can import this file into `index.css`.

- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 71

**Comment by n817** [comment]
Hello! I'm glad to say that you've done a really good job! Your project has been accepted.
I wish you success in the next stage and in your future projects!✨

Number of points: 85

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* `Roboto` font is not rendered on the page, because font files are not connected. 
It's necessary to connect `fonts.css`.
* On tablet 768px:
    - The project doesn't match the design, it's necessary to fix it. The project should match the design in the Figma.

* On mobile 320px:
    - The project doesn't match the design, it's necessary to fix it. The project should match the design in the Figma.

You can use PerfectPixel plugin to compare your project with the design: https://www.welldonecode.com/perfectpixel/

- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

- [x]  Classes are named according to BEM specifications.

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.

* It's necessary to connect `fonts.css`. You can import this file into `index.css`.

- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 85

**Pull request merged**
